In [2]:
import numpy as np
np.random.seed(42)
# A =  X  1
A = np.array ( [
[1 , 2.0],
[1 , 3.0],
[1 , 4.5],
[1 , 5.5]
] )
# y =
y = np.array ( [
[3.1],
[4.9],
[8.2],
[10.1]
] )
m = len ( y )


In [3]:
theta_normal = np.linalg.inv(A.T @ A) @ A.T @ y
print(theta_normal)

[[-1.04137931]
 [ 2.03103448]]


In [6]:
m = len(y)
theta = np.zeros((2, 1))
learning_rate = 0.01
n_iterations = 1000

for iteration in range(n_iterations):
    gradients = (1/m) * A.T @ (A @ theta - y)
    theta = theta - learning_rate * gradients

print(theta)

[[-0.55217831]
 [ 1.9146829 ]]


In [7]:
U, s, Vt = np.linalg.svd(A, full_matrices=False)
s_inv = np.diag(1 / s)
A_pinv = Vt.T @ s_inv @ U.T
theta_svd = A_pinv @ y

print(theta_svd)

[[-1.04137931]
 [ 2.03103448]]


In [37]:
m = len(y)
# noise = np.random.rand(m, 1)
noise = np.zeros((m,1))

A_collinear = np.hstack((A, A[:, [1]] + noise))
print(A_collinear)

theta_normal_collinear = np.linalg.inv(A_collinear.T @ A_collinear) @ A_collinear.T @ y
print("\n", theta_normal_collinear)
print("\n[" + "]\n[".join([f"{x[0]:.8f}" for x in theta_normal_collinear]) + "]")

[[1.  2.  2. ]
 [1.  3.  3. ]
 [1.  4.5 4.5]
 [1.  5.5 5.5]]


LinAlgError: Singular matrix

In [39]:
U, s, Vt = np.linalg.svd(A_collinear, full_matrices=False)
s_inv = np.diag(1 / s)
A_pinv = Vt.T @ s_inv @ U.T
theta_svd_collinear = A_pinv @ y

print(theta_svd_collinear)
print("\n[" + "]\n[".join([f"{x[0]:.8f}" for x in theta_svd_collinear]) + "]")

[[-1.04137931e+00]
 [-2.36400575e+15]
 [ 2.36400575e+15]]

[-1.04137931]
[-2364005752194400.00000000]
[2364005752194400.00000000]
