In [2]:
import numpy as np
np.random.seed(42)
# A =  X  1
A = np.array ( [
[1 , 2.0],
[1 , 3.0],
[1 , 4.5],
[1 , 5.5]
] )
# y =
y = np.array ( [
[3.1],
[4.9],
[8.2],
[10.1]
] )
m = len ( y )


In [3]:
theta_normal = np.linalg.inv(A.T @ A) @ A.T @ y
print(theta_normal)

[[-1.04137931]
 [ 2.03103448]]


In [6]:
m = len(y)
theta = np.zeros((2, 1))
learning_rate = 0.01
n_iterations = 1000

for iteration in range(n_iterations):
    gradients = (1/m) * A.T @ (A @ theta - y)
    theta = theta - learning_rate * gradients

print(theta)

[[-0.55217831]
 [ 1.9146829 ]]


In [7]:
U, s, Vt = np.linalg.svd(A, full_matrices=False)
s_inv = np.diag(1 / s)
A_pinv = Vt.T @ s_inv @ U.T
theta_svd = A_pinv @ y

print(theta_svd)

[[-1.04137931]
 [ 2.03103448]]
